server:
  port: 9090
  servlet:
    context-path: /alertmanage

spring:
  redis-alert:
    database: 0   # Redis数据库索引（默认为0）
    host: 10.6.1.22  # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password: Yixin4redis   # Redis服务器连接密码（默认为空）
    timeout: 0  # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 32 # 接池最大连接数（使用负值表示没有限制）
        max-wait: 5000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
alert:
  config:
    restrain:
      ip:
        interval: 10
        maxCount: 200
        lockTime: 5
      mobile:
        interval: 60
        maxCount: 5
        lockTime: 5