server:
  port: 8066
  servlet:
    context-path: /alertmanage

spring:
  redis-alert:
    host: 10.6.1.22
    port: 6379
    timeout: 500
    password: Yixin4redis
    jedis:
      pool:
        max-active: 32 # 接池最大连接数（使用负值表示没有限制）
        max-wait: 5000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
  #    cluster:
  #      #nodes: 172.20.4.85:7000,172.20.4.85:7001,172.20.4.86:7002,172.20.4.86:7003,172.20.4.87:7004,172.20.4.87:7005
  #      nodes: 10.6.1.22:6379
  #      max-redirects: 3